### ISSUE TITLE
Need a scroll

### ISSUE THREAD

**Issue by deikatsuo** [HarlemSquirrel/gnome-emoji-buckets#1]
![screenshot from 2017-02-07 08-52-28](https://cloud.githubusercontent.com/assets/8337409/22674677/d8b890f4-ed13-11e6-945f-92071237e36f.png)

**Comment by HarlemSquirrel** [comment]
Maybe having more emojis per line would be better?

**Comment by deikatsuo** [comment]
I dont think so, its already fill up my whole screen. Would be nice if you could make ( the canvas ) it be smaller

**Comment by deikatsuo** [comment]
![ezgif com-17a60f9599](https://cloud.githubusercontent.com/assets/8337409/22686933/b80083f4-ed58-11e6-9807-be7208bf4cac.gif)

**Comment by HarlemSquirrel** [comment]
Nice gif! I'm working on a setting to allow adjusting the emoji font size. Stay tuned!

**Comment by HarlemSquirrel** [comment]
I just pushed a new commit that adds this one preference. Let me know what you think!

**Comment by deikatsuo** [comment]
thats really good. thks
